name: at_mcp_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dart_mcp: ^0.3.2
  at_client: ^3.3.0
  at_onboarding_cli: ^1.11.0
  at_utils: ^3.2.0
  logging: ^1.3.0
  http: ^1.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
